const data = [
    {
    id: "T01",
    jenisTanaman: "Bayam",
    namaPengingat: "Pengingat 1",
    waktu: "17.00",
    pengulangan: "10 Hari Sekali",
  },
  {
    id: "T02",
    jenisTanaman: "Cabe",
    namaPengingat: "Pengingat 1",
    waktu: "05.00/06.00",
    pengulangan: "22 Hari Sekali",
  },
  {
    id: "T03",
    jenisTanaman: "Kol",
    namaPengingat: "Pengingat 1",
    waktu: "05.00/06.00",
    pengulangan: "25 Hari Sekali",
  },
  {
    id: "T04",
    jenisTanaman: "Tomat",
    namaPengingat: "Pengingat 1",
    waktu: "08.00/10.00/12.00",
    pengulangan: "18 Hari Sekali",
  },
  {
    id: "T05",
    jenisTanaman: "Bawang",
    namaPengingat: "Pengingat 1",
    waktu: "15.00",
    pengulangan: "12 Hari Sekali",
  },
  {
    id: "T06",
    jenisTanaman: "Anggur",
    namaPengingat: "Pengingat 1",
    waktu: "07.00/18.00",
    pengulangan: "20 Hari Sekali",
  },
  {
    id: "T07",
    jenisTanaman: "Pepaya",
    namaPengingat: "Pengingat 1",
    waktu: "09.00",
    pengulangan: "15 Hari Sekali",
  },
  {
    id: "T08",
    jenisTanaman: "Lobak",
    namaPengingat: "Pengingat 2",
    waktu: "16.00",
    pengulangan: "14 Hari Sekali",
  },
  {
    id: "T09",
    jenisTanaman: "Mangga",
    namaPengingat: "Pengingat 2",
    waktu: "06.00/19.00",
    pengulangan: "21 Hari Sekali",
  },
  {
    id: "T10",
    jenisTanaman: "Jeruk",
    namaPengingat: "Pengingat 2",
    waktu: "10.00",
    pengulangan: "17 Hari Sekali",
  },
  {
    id: "T11",
    jenisTanaman: "Pisang",
    namaPengingat: "Pengingat 2",
    waktu: "08.00/17.00",
    pengulangan: "19 Hari Sekali",
  },
  {
    id: "T12",
    jenisTanaman: "Melon",
    namaPengingat: "Pengingat 2",
    waktu: "11.00",
    pengulangan: "23 Hari Sekali",
  },
  {
    id: "T13",
    jenisTanaman: "Wortel",
    namaPengingat: "Pengingat 2",
    waktu: "14.00",
    pengulangan: "13 Hari Sekali",
  },
  {
    id: "T14",
    jenisTanaman: "Terong",
    namaPengingat: "Pengingat 3",
    waktu: "07.00/18.00",
    pengulangan: "24 Hari Sekali",
  },
  {
    id: "T15",
    jenisTanaman: "Labu",
    namaPengingat: "Pengingat 3",
    waktu: "12.00",
    pengulangan: "16 Hari Sekali",
  },
]
export default data;