const data = [
    {
    id: "T01",
    namaTanaman: "Bayam",
    penyiraman: "2 Hari Sekali",
    waktuPenyiraman: "17.00",
    pemberianPupuk: "10 Hari Sekali",
    waktuPemberianPupuk: "17.00",
  },
  {
    id: "T02",
    namaTanaman: "Cabe",
    penyiraman: "3 Hari 2 Kali",
    waktuPenyiraman: "05.00/06.00",
    pemberianPupuk: "22 Hari Sekali",
    waktuPemberianPupuk: "05.00",
  },
  {
    id: "T03",
    namaTanaman: "Kol",
    penyiraman: "3 Hari 2 Kali",
    waktuPenyiraman: "05.00/06.00",
    pemberianPupuk: "25 Hari Sekali",
    waktuPemberianPupuk: "05.00",
  },
  {
    id: "T04",
    namaTanaman: "Tomat",
    penyiraman: "4 Hari 3 Kali",
    waktuPenyiraman: "08.00/10.00/12.00",
    pemberianPupuk: "18 Hari Sekali",
    waktuPemberianPupuk: "08.00",
  },
  {
    id: "T05",
    namaTanaman: "Bawang",
    penyiraman: "2 Hari Sekali",
    waktuPenyiraman: "15.00",
    pemberianPupuk: "12 Hari Sekali",
    waktuPemberianPupuk: "15.00",
  },
  {
    id: "T06",
    namaTanaman: "Anggur",
    penyiraman: "5 Hari 2 Kali",
    waktuPenyiraman: "07.00/18.00",
    pemberianPupuk: "20 Hari Sekali",
    waktuPemberianPupuk: "07.00",
  },
  {
    id: "T07",
    namaTanaman: "Pepaya",
    penyiraman: "3 Hari 1 Kali",
    waktuPenyiraman: "09.00",
    pemberianPupuk: "15 Hari Sekali",
    waktuPemberianPupuk: "09.00",
  },
  {
    id: "T08",
    namaTanaman: "Lobak",
    penyiraman: "2 Hari Sekali",
    waktuPenyiraman: "16.00",
    pemberianPupuk: "14 Hari Sekali",
    waktuPemberianPupuk: "16.00",
  },
  {
    id: "T09",
    namaTanaman: "Mangga",
    penyiraman: "4 Hari 2 Kali",
    waktuPenyiraman: "06.00/19.00",
    pemberianPupuk: "21 Hari Sekali",
    waktuPemberianPupuk: "06.00",
  },
  {
    id: "T10",
    namaTanaman: "Jeruk",
    penyiraman: "3 Hari 1 Kali",
    waktuPenyiraman: "10.00",
    pemberianPupuk: "17 Hari Sekali",
    waktuPemberianPupuk: "10.00",
  },
  {
    id: "T11",
    namaTanaman: "Pisang",
    penyiraman: "5 Hari 2 Kali",
    waktuPenyiraman: "08.00/17.00",
    pemberianPupuk: "19 Hari Sekali",
    waktuPemberianPupuk: "08.00",
  },
  {
    id: "T12",
    namaTanaman: "Melon",
    penyiraman: "4 Hari 1 Kali",
    waktuPenyiraman: "11.00",
    pemberianPupuk: "23 Hari Sekali",
    waktuPemberianPupuk: "11.00",
  },
  {
    id: "T13",
    namaTanaman: "Wortel",
    penyiraman: "2 Hari Sekali",
    waktuPenyiraman: "14.00",
    pemberianPupuk: "13 Hari Sekali",
    waktuPemberianPupuk: "14.00",
  },
  {
    id: "T14",
    namaTanaman: "Terong",
    penyiraman: "3 Hari 2 Kali",
    waktuPenyiraman: "07.00/18.00",
    pemberianPupuk: "24 Hari Sekali",
    waktuPemberianPupuk: "07.00",
  },
  {
    id: "T15",
    namaTanaman: "Labu",
    penyiraman: "4 Hari 1 Kali",
    waktuPenyiraman: "12.00",
    pemberianPupuk: "16 Hari Sekali",
    waktuPemberianPupuk: "12.00",
  },
  {
    id: "T16",
    namaTanaman: "Pepes",
    penyiraman: "2 Hari Sekali",
    waktuPenyiraman: "13.00",
    pemberianPupuk: "11 Hari Sekali",
    waktuPemberianPupuk: "13.00",
  },
  {
    id: "T17",
    namaTanaman: "Sawo",
    penyiraman: "3 Hari 1 Kali",
    waktuPenyiraman: "09.00",
    pemberianPupuk: "26 Hari Sekali",
    waktuPemberianPupuk: "09.00",
  },
  {
    id: "T18",
    namaTanaman: "Sirsak",
    penyiraman: "5 Hari 2 Kali",
    waktuPenyiraman: "08.00/17.00",
    pemberianPupuk: "27 Hari Sekali",
    waktuPemberianPupuk: "08.00",
  },
  {
    id: "T19",
    namaTanaman: "Markisa",
    penyiraman: "4 Hari 1 Kali",
    waktuPenyiraman: "11.00",
    pemberianPupuk: "28 Hari Sekali",
    waktuPemberianPupuk: "11.00",
  },
  {
    id: "T20",
    namaTanaman: "Pare",
    penyiraman: "3 Hari 2 Kali",
    waktuPenyiraman: "07.00/18.00",
    pemberianPupuk: "29 Hari Sekali",
    waktuPemberianPupuk: "07.00",
  },
  {
    id: "T21",
    namaTanaman: "Belimbing",
    penyiraman: "2 Hari Sekali",
    waktuPenyiraman: "14.00",
    pemberianPupuk: "30 Hari Sekali",
    waktuPemberianPupuk: "14.00",
  },
  {
    id: "T22",
    namaTanaman: "Durian",
    penyiraman: "3 Hari 1 Kali",
    waktuPenyiraman: "09.00",
    pemberianPupuk: "31 Hari Sekali",
    waktuPemberianPupuk: "09.00",
  },
  {
    id: "T23",
    namaTanaman: "Srikaya",
    penyiraman: "5 Hari 2 Kali",
    waktuPenyiraman: "08.00/17.00",
    pemberianPupuk: "32 Hari Sekali",
    waktuPemberianPupuk: "08.00",
  },
  {
    id: "T24",
    namaTanaman: "Pomelo",
    penyiraman: "4 Hari 1 Kali",
    waktuPenyiraman: "11.00",
    pemberianPupuk: "33 Hari Sekali",
    waktuPemberianPupuk: "11.00",
  },
  {
    id: "T25",
    namaTanaman: "Jambu Air",
    penyiraman: "2 Hari Sekali",
    waktuPenyiraman: "14.00",
    pemberianPupuk: "34 Hari Sekali",
    waktuPemberianPupuk: "14.00",
  },
  {
    id: "T26",
    namaTanaman: "Cempedak",
    penyiraman: "3 Hari 1 Kali",
    waktuPenyiraman: "09.00",
    pemberianPupuk: "35 Hari Sekali",
    waktuPemberianPupuk: "09.00",
  },
  {
    id: "T27",
    namaTanaman: "Salak",
    penyiraman: "5 Hari 2 Kali",
    waktuPenyiraman: "08.00/17.00",
    pemberianPupuk: "36 Hari Sekali",
    waktuPemberianPupuk: "08.00",
  },
  {
    id: "T28",
    namaTanaman: "Rambutan",
    penyiraman: "4 Hari 1 Kali",
    waktuPenyiraman: "11.00",
    pemberianPupuk: "37 Hari Sekali",
    waktuPemberianPupuk: "11.00",
  },
  {
    id: "T29",
    namaTanaman: "Nangka",
    penyiraman: "2 Hari Sekali",
    waktuPenyiraman: "14.00",
    pemberianPupuk: "38 Hari Sekali",
    waktuPemberianPupuk: "14.00",
  },
  {
    id: "T30",
    namaTanaman: "Manggis",
    penyiraman: "3 Hari 1 Kali",
    waktuPenyiraman: "09.00",
    pemberianPupuk: "39 Hari Sekali",
    waktuPemberianPupuk: "09.00",
  },{
      id: "T01",
      namaTanaman: "Bayam",
      penyiraman: "2 Hari Sekali",
      waktuPenyiraman: "17.00",
      pemberianPupuk: "10 Hari Sekali",
      waktuPemberianPupuk: "17.00",
    },
    {
      id: "T02",
      namaTanaman: "Cabe",
      penyiraman: "3 Hari 2 Kali",
      waktuPenyiraman: "05.00/06.00",
      pemberianPupuk: "22 Hari Sekali",
      waktuPemberianPupuk: "05.00",
    },
    {
      id: "T03",
      namaTanaman: "Kol",
      penyiraman: "3 Hari 2 Kali",
      waktuPenyiraman: "05.00/06.00",
      pemberianPupuk: "25 Hari Sekali",
      waktuPemberianPupuk: "05.00",
    },
    {
      id: "T04",
      namaTanaman: "Tomat",
      penyiraman: "4 Hari 3 Kali",
      waktuPenyiraman: "08.00/10.00/12.00",
      pemberianPupuk: "18 Hari Sekali",
      waktuPemberianPupuk: "08.00",
    },
    {
      id: "T05",
      namaTanaman: "Bawang",
      penyiraman: "2 Hari Sekali",
      waktuPenyiraman: "15.00",
      pemberianPupuk: "12 Hari Sekali",
      waktuPemberianPupuk: "15.00",
    },
    {
      id: "T06",
      namaTanaman: "Anggur",
      penyiraman: "5 Hari 2 Kali",
      waktuPenyiraman: "07.00/18.00",
      pemberianPupuk: "20 Hari Sekali",
      waktuPemberianPupuk: "07.00",
    },
    {
      id: "T07",
      namaTanaman: "Pepaya",
      penyiraman: "3 Hari 1 Kali",
      waktuPenyiraman: "09.00",
      pemberianPupuk: "15 Hari Sekali",
      waktuPemberianPupuk: "09.00",
    },
    {
      id: "T08",
      namaTanaman: "Lobak",
      penyiraman: "2 Hari Sekali",
      waktuPenyiraman: "16.00",
      pemberianPupuk: "14 Hari Sekali",
      waktuPemberianPupuk: "16.00",
    },
    {
      id: "T09",
      namaTanaman: "Mangga",
      penyiraman: "4 Hari 2 Kali",
      waktuPenyiraman: "06.00/19.00",
      pemberianPupuk: "21 Hari Sekali",
      waktuPemberianPupuk: "06.00",
    },
    {
      id: "T10",
      namaTanaman: "Jeruk",
      penyiraman: "3 Hari 1 Kali",
      waktuPenyiraman: "10.00",
      pemberianPupuk: "17 Hari Sekali",
      waktuPemberianPupuk: "10.00",
    },
    {
      id: "T11",
      namaTanaman: "Pisang",
      penyiraman: "5 Hari 2 Kali",
      waktuPenyiraman: "08.00/17.00",
      pemberianPupuk: "19 Hari Sekali",
      waktuPemberianPupuk: "08.00",
    },
    {
      id: "T12",
      namaTanaman: "Melon",
      penyiraman: "4 Hari 1 Kali",
      waktuPenyiraman: "11.00",
      pemberianPupuk: "23 Hari Sekali",
      waktuPemberianPupuk: "11.00",
    },
    {
      id: "T13",
      namaTanaman: "Wortel",
      penyiraman: "2 Hari Sekali",
      waktuPenyiraman: "14.00",
      pemberianPupuk: "13 Hari Sekali",
      waktuPemberianPupuk: "14.00",
    },
    {
      id: "T14",
      namaTanaman: "Terong",
      penyiraman: "3 Hari 2 Kali",
      waktuPenyiraman: "07.00/18.00",
      pemberianPupuk: "24 Hari Sekali",
      waktuPemberianPupuk: "07.00",
    },
    {
      id: "T15",
      namaTanaman: "Labu",
      penyiraman: "4 Hari 1 Kali",
      waktuPenyiraman: "12.00",
      pemberianPupuk: "16 Hari Sekali",
      waktuPemberianPupuk: "12.00",
    },
    {
      id: "T16",
      namaTanaman: "Pepes",
      penyiraman: "2 Hari Sekali",
      waktuPenyiraman: "13.00",
      pemberianPupuk: "11 Hari Sekali",
      waktuPemberianPupuk: "13.00",
    },
    {
      id: "T17",
      namaTanaman: "Sawo",
      penyiraman: "3 Hari 1 Kali",
      waktuPenyiraman: "09.00",
      pemberianPupuk: "26 Hari Sekali",
      waktuPemberianPupuk: "09.00",
    },
    {
      id: "T18",
      namaTanaman: "Sirsak",
      penyiraman: "5 Hari 2 Kali",
      waktuPenyiraman: "08.00/17.00",
      pemberianPupuk: "27 Hari Sekali",
      waktuPemberianPupuk: "08.00",
    },
    {
      id: "T19",
      namaTanaman: "Markisa",
      penyiraman: "4 Hari 1 Kali",
      waktuPenyiraman: "11.00",
      pemberianPupuk: "28 Hari Sekali",
      waktuPemberianPupuk: "11.00",
    },
    {
      id: "T20",
      namaTanaman: "Pare",
      penyiraman: "3 Hari 2 Kali",
      waktuPenyiraman: "07.00/18.00",
      pemberianPupuk: "29 Hari Sekali",
      waktuPemberianPupuk: "07.00",
    },
    {
      id: "T21",
      namaTanaman: "Belimbing",
      penyiraman: "2 Hari Sekali",
      waktuPenyiraman: "14.00",
      pemberianPupuk: "30 Hari Sekali",
      waktuPemberianPupuk: "14.00",
    },
    {
      id: "T22",
      namaTanaman: "Durian",
      penyiraman: "3 Hari 1 Kali",
      waktuPenyiraman: "09.00",
      pemberianPupuk: "31 Hari Sekali",
      waktuPemberianPupuk: "09.00",
    },
    {
      id: "T23",
      namaTanaman: "Srikaya",
      penyiraman: "5 Hari 2 Kali",
      waktuPenyiraman: "08.00/17.00",
      pemberianPupuk: "32 Hari Sekali",
      waktuPemberianPupuk: "08.00",
    },
    {
      id: "T24",
      namaTanaman: "Pomelo",
      penyiraman: "4 Hari 1 Kali",
      waktuPenyiraman: "11.00",
      pemberianPupuk: "33 Hari Sekali",
      waktuPemberianPupuk: "11.00",
    },
    {
      id: "T25",
      namaTanaman: "Jambu Air",
      penyiraman: "2 Hari Sekali",
      waktuPenyiraman: "14.00",
      pemberianPupuk: "34 Hari Sekali",
      waktuPemberianPupuk: "14.00",
    },
    {
      id: "T26",
      namaTanaman: "Cempedak",
      penyiraman: "3 Hari 1 Kali",
      waktuPenyiraman: "09.00",
      pemberianPupuk: "35 Hari Sekali",
      waktuPemberianPupuk: "09.00",
    },
    {
      id: "T27",
      namaTanaman: "Salak",
      penyiraman: "5 Hari 2 Kali",
      waktuPenyiraman: "08.00/17.00",
      pemberianPupuk: "36 Hari Sekali",
      waktuPemberianPupuk: "08.00",
    },
    {
      id: "T28",
      namaTanaman: "Rambutan",
      penyiraman: "4 Hari 1 Kali",
      waktuPenyiraman: "11.00",
      pemberianPupuk: "37 Hari Sekali",
      waktuPemberianPupuk: "11.00",
    },
    {
      id: "T29",
      namaTanaman: "Nangka",
      penyiraman: "2 Hari Sekali",
      waktuPenyiraman: "14.00",
      pemberianPupuk: "38 Hari Sekali",
      waktuPemberianPupuk: "14.00",
    },
    {
      id: "T30",
      namaTanaman: "Manggis",
      penyiraman: "3 Hari 1 Kali",
      waktuPenyiraman: "09.00",
      pemberianPupuk: "39 Hari Sekali",
      waktuPemberianPupuk: "09.00",
    },{
      id: "T01",
      namaTanaman: "Bayam",
      penyiraman: "2 Hari Sekali",
      waktuPenyiraman: "17.00",
      pemberianPupuk: "10 Hari Sekali",
      waktuPemberianPupuk: "17.00",
    },
    {
      id: "T02",
      namaTanaman: "Cabe",
      penyiraman: "3 Hari 2 Kali",
      waktuPenyiraman: "05.00/06.00",
      pemberianPupuk: "22 Hari Sekali",
      waktuPemberianPupuk: "05.00",
    },
    {
      id: "T03",
      namaTanaman: "Kol",
      penyiraman: "3 Hari 2 Kali",
      waktuPenyiraman: "05.00/06.00",
      pemberianPupuk: "25 Hari Sekali",
      waktuPemberianPupuk: "05.00",
    },
    {
      id: "T04",
      namaTanaman: "Tomat",
      penyiraman: "4 Hari 3 Kali",
      waktuPenyiraman: "08.00/10.00/12.00",
      pemberianPupuk: "18 Hari Sekali",
      waktuPemberianPupuk: "08.00",
    },
    {
      id: "T05",
      namaTanaman: "Bawang",
      penyiraman: "2 Hari Sekali",
      waktuPenyiraman: "15.00",
      pemberianPupuk: "12 Hari Sekali",
      waktuPemberianPupuk: "15.00",
    },
    {
      id: "T06",
      namaTanaman: "Anggur",
      penyiraman: "5 Hari 2 Kali",
      waktuPenyiraman: "07.00/18.00",
      pemberianPupuk: "20 Hari Sekali",
      waktuPemberianPupuk: "07.00",
    },
    {
      id: "T07",
      namaTanaman: "Pepaya",
      penyiraman: "3 Hari 1 Kali",
      waktuPenyiraman: "09.00",
      pemberianPupuk: "15 Hari Sekali",
      waktuPemberianPupuk: "09.00",
    },
    {
      id: "T08",
      namaTanaman: "Lobak",
      penyiraman: "2 Hari Sekali",
      waktuPenyiraman: "16.00",
      pemberianPupuk: "14 Hari Sekali",
      waktuPemberianPupuk: "16.00",
    },
    {
      id: "T09",
      namaTanaman: "Mangga",
      penyiraman: "4 Hari 2 Kali",
      waktuPenyiraman: "06.00/19.00",
      pemberianPupuk: "21 Hari Sekali",
      waktuPemberianPupuk: "06.00",
    },
    {
      id: "T10",
      namaTanaman: "Jeruk",
      penyiraman: "3 Hari 1 Kali",
      waktuPenyiraman: "10.00",
      pemberianPupuk: "17 Hari Sekali",
      waktuPemberianPupuk: "10.00",
    },
    {
      id: "T11",
      namaTanaman: "Pisang",
      penyiraman: "5 Hari 2 Kali",
      waktuPenyiraman: "08.00/17.00",
      pemberianPupuk: "19 Hari Sekali",
      waktuPemberianPupuk: "08.00",
    },
    {
      id: "T12",
      namaTanaman: "Melon",
      penyiraman: "4 Hari 1 Kali",
      waktuPenyiraman: "11.00",
      pemberianPupuk: "23 Hari Sekali",
      waktuPemberianPupuk: "11.00",
    },
    {
      id: "T13",
      namaTanaman: "Wortel",
      penyiraman: "2 Hari Sekali",
      waktuPenyiraman: "14.00",
      pemberianPupuk: "13 Hari Sekali",
      waktuPemberianPupuk: "14.00",
    },
    {
      id: "T14",
      namaTanaman: "Terong",
      penyiraman: "3 Hari 2 Kali",
      waktuPenyiraman: "07.00/18.00",
      pemberianPupuk: "24 Hari Sekali",
      waktuPemberianPupuk: "07.00",
    },
    {
      id: "T15",
      namaTanaman: "Labu",
      penyiraman: "4 Hari 1 Kali",
      waktuPenyiraman: "12.00",
      pemberianPupuk: "16 Hari Sekali",
      waktuPemberianPupuk: "12.00",
    },
    {
      id: "T16",
      namaTanaman: "Pepes",
      penyiraman: "2 Hari Sekali",
      waktuPenyiraman: "13.00",
      pemberianPupuk: "11 Hari Sekali",
      waktuPemberianPupuk: "13.00",
    },
    {
      id: "T17",
      namaTanaman: "Sawo",
      penyiraman: "3 Hari 1 Kali",
      waktuPenyiraman: "09.00",
      pemberianPupuk: "26 Hari Sekali",
      waktuPemberianPupuk: "09.00",
    },
    {
      id: "T18",
      namaTanaman: "Sirsak",
      penyiraman: "5 Hari 2 Kali",
      waktuPenyiraman: "08.00/17.00",
      pemberianPupuk: "27 Hari Sekali",
      waktuPemberianPupuk: "08.00",
    },
    {
      id: "T19",
      namaTanaman: "Markisa",
      penyiraman: "4 Hari 1 Kali",
      waktuPenyiraman: "11.00",
      pemberianPupuk: "28 Hari Sekali",
      waktuPemberianPupuk: "11.00",
    },
    {
      id: "T20",
      namaTanaman: "Pare",
      penyiraman: "3 Hari 2 Kali",
      waktuPenyiraman: "07.00/18.00",
      pemberianPupuk: "29 Hari Sekali",
      waktuPemberianPupuk: "07.00",
    },
    {
      id: "T21",
      namaTanaman: "Belimbing",
      penyiraman: "2 Hari Sekali",
      waktuPenyiraman: "14.00",
      pemberianPupuk: "30 Hari Sekali",
      waktuPemberianPupuk: "14.00",
    },
    {
      id: "T22",
      namaTanaman: "Durian",
      penyiraman: "3 Hari 1 Kali",
      waktuPenyiraman: "09.00",
      pemberianPupuk: "31 Hari Sekali",
      waktuPemberianPupuk: "09.00",
    },
    {
      id: "T23",
      namaTanaman: "Srikaya",
      penyiraman: "5 Hari 2 Kali",
      waktuPenyiraman: "08.00/17.00",
      pemberianPupuk: "32 Hari Sekali",
      waktuPemberianPupuk: "08.00",
    },
    {
      id: "T24",
      namaTanaman: "Pomelo",
      penyiraman: "4 Hari 1 Kali",
      waktuPenyiraman: "11.00",
      pemberianPupuk: "33 Hari Sekali",
      waktuPemberianPupuk: "11.00",
    },
    {
      id: "T25",
      namaTanaman: "Jambu Air",
      penyiraman: "2 Hari Sekali",
      waktuPenyiraman: "14.00",
      pemberianPupuk: "34 Hari Sekali",
      waktuPemberianPupuk: "14.00",
    },
    {
      id: "T26",
      namaTanaman: "Cempedak",
      penyiraman: "3 Hari 1 Kali",
      waktuPenyiraman: "09.00",
      pemberianPupuk: "35 Hari Sekali",
      waktuPemberianPupuk: "09.00",
    },
    {
      id: "T27",
      namaTanaman: "Salak",
      penyiraman: "5 Hari 2 Kali",
      waktuPenyiraman: "08.00/17.00",
      pemberianPupuk: "36 Hari Sekali",
      waktuPemberianPupuk: "08.00",
    },
    {
      id: "T28",
      namaTanaman: "Rambutan",
      penyiraman: "4 Hari 1 Kali",
      waktuPenyiraman: "11.00",
      pemberianPupuk: "37 Hari Sekali",
      waktuPemberianPupuk: "11.00",
    },
    {
      id: "T29",
      namaTanaman: "Nangka",
      penyiraman: "2 Hari Sekali",
      waktuPenyiraman: "14.00",
      pemberianPupuk: "38 Hari Sekali",
      waktuPemberianPupuk: "14.00",
    },
    {
      id: "T30",
      namaTanaman: "Manggis",
      penyiraman: "3 Hari 1 Kali",
      waktuPenyiraman: "09.00",
      pemberianPupuk: "39 Hari Sekali",
      waktuPemberianPupuk: "09.00",
    },
]
export default data;